server:
  port: 7080

eureka:
  instance:
    hostname: inst2
  client:
    serviceUrl:
      defaultZone: http://inst1:7000/eureka/
ribbon:
  ConnectTimeout: 90000000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 90000000 #请求处理的超时时间